version: "3"
services:
  # フロントエンド
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000" # 開発用
    command: yarn dev

  # データベース
  database:
    image: mysql:8.3.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
