version: "3"
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000" # 開発用
    command: yarn dev
