version: "3"
services:
  app:
    build: .
    container_name: docker-next-setting
    volumes:
      - ./my-app:/app
      - /app/node_modules
    ports:
      - "3000:3000" # 開発用
    command: yarn dev
